activate: Regular
schedule:
  - 
    name: Regular
    working:
      - 09:00-10:00 : 背英语
      - 10:10-11:10 : 数学
      - 11:20-12:20 : 数学
      - 13:30-14:30 : 计组408
      - 14:40-15:40 : 计组408
      - 15:50-16:50 : 计组408
      - 17:00-18:00 : 计组408
      - 19:00-20:00 : 考研任选范围
      - 20:10-21:10 : 自由编程
      # - 23:33-23:40 : hehe
    img_dir: E:\twitter_media\Dormicumproject
    audio_dir_when_start: D:\coding\gptsovits_infer_api\output\现在该继续学习了哟
    audio_dir_when_end: D:\coding\gptsovits_infer_api\output\现在是休息时间哦